// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FILE_FILE_H_
#define FLATBUFFERS_GENERATED_FILE_FILE_H_

#include "flatbuffers/flatbuffers.h"

namespace file {

struct Codec;

struct H265FrameHeader;

struct H264FrameHeader;

struct JPEGFrameHeader;

struct MetadataFrameHeader;

struct MPEG4FrameHeader;

struct Track;

struct Recording;

struct Device;

struct File;

enum class FrameHeaderType : int8_t {
  H264 = 1,
  JPEG = 2,
  METADATA = 3,
  MPEG4 = 4,
  H265 = 5,
  MIN = H264,
  MAX = H265
};

inline const FrameHeaderType (&EnumValuesFrameHeaderType())[5] {
  static const FrameHeaderType values[] = {
    FrameHeaderType::H264,
    FrameHeaderType::JPEG,
    FrameHeaderType::METADATA,
    FrameHeaderType::MPEG4,
    FrameHeaderType::H265
  };
  return values;
}

inline const char * const *EnumNamesFrameHeaderType() {
  static const char * const names[6] = {
    "H264",
    "JPEG",
    "METADATA",
    "MPEG4",
    "H265",
    nullptr
  };
  return names;
}

inline const char *EnumNameFrameHeaderType(FrameHeaderType e) {
  if (e < FrameHeaderType::H264 || e > FrameHeaderType::H265) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(FrameHeaderType::H264);
  return EnumNamesFrameHeaderType()[index];
}

struct Codec FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_CODEC = 6,
    VT_PARAMETERS = 8
  };
  uint64_t index() const {
    return GetField<uint64_t>(VT_INDEX, 0);
  }
  int32_t codec() const {
    return GetField<int32_t>(VT_CODEC, 0);
  }
  const flatbuffers::String *parameters() const {
    return GetPointer<const flatbuffers::String *>(VT_PARAMETERS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INDEX) &&
           VerifyField<int32_t>(verifier, VT_CODEC) &&
           VerifyOffset(verifier, VT_PARAMETERS) &&
           verifier.VerifyString(parameters()) &&
           verifier.EndTable();
  }
};

struct CodecBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_index(uint64_t index) {
    fbb_.AddElement<uint64_t>(Codec::VT_INDEX, index, 0);
  }
  void add_codec(int32_t codec) {
    fbb_.AddElement<int32_t>(Codec::VT_CODEC, codec, 0);
  }
  void add_parameters(flatbuffers::Offset<flatbuffers::String> parameters) {
    fbb_.AddOffset(Codec::VT_PARAMETERS, parameters);
  }
  explicit CodecBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  CodecBuilder &operator=(const CodecBuilder &);
  flatbuffers::Offset<Codec> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Codec>(end);
    return o;
  }
};

inline flatbuffers::Offset<Codec> CreateCodec(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    int32_t codec = 0,
    flatbuffers::Offset<flatbuffers::String> parameters = 0) {
  CodecBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_parameters(parameters);
  builder_.add_codec(codec);
  return builder_.Finish();
}

inline flatbuffers::Offset<Codec> CreateCodecDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    int32_t codec = 0,
    const char *parameters = nullptr) {
  auto parameters__ = parameters ? _fbb.CreateString(parameters) : 0;
  return file::CreateCodec(
      _fbb,
      index,
      codec,
      parameters__);
}

struct H265FrameHeader FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODECINDEX = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_MARKER = 10,
    VT_TIME = 12,
    VT_SIGNATURE = 14,
    VT_DONLFIELD = 16,
    VT_OFFSETS = 18
  };
  uint64_t codecindex() const {
    return GetField<uint64_t>(VT_CODECINDEX, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  const flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  bool donlfield() const {
    return GetField<uint8_t>(VT_DONLFIELD, 0) != 0;
  }
  const flatbuffers::Vector<uint32_t> *offsets() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_OFFSETS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CODECINDEX) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_MARKER) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           VerifyField<uint8_t>(verifier, VT_DONLFIELD) &&
           VerifyOffset(verifier, VT_OFFSETS) &&
           verifier.VerifyVector(offsets()) &&
           verifier.EndTable();
  }
};

struct H265FrameHeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_codecindex(uint64_t codecindex) {
    fbb_.AddElement<uint64_t>(H265FrameHeader::VT_CODECINDEX, codecindex, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(H265FrameHeader::VT_OFFSET, offset, 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(H265FrameHeader::VT_SIZE, size, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(H265FrameHeader::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(H265FrameHeader::VT_TIME, time, 0);
  }
  void add_signature(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(H265FrameHeader::VT_SIGNATURE, signature);
  }
  void add_donlfield(bool donlfield) {
    fbb_.AddElement<uint8_t>(H265FrameHeader::VT_DONLFIELD, static_cast<uint8_t>(donlfield), 0);
  }
  void add_offsets(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> offsets) {
    fbb_.AddOffset(H265FrameHeader::VT_OFFSETS, offsets);
  }
  explicit H265FrameHeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  H265FrameHeaderBuilder &operator=(const H265FrameHeaderBuilder &);
  flatbuffers::Offset<H265FrameHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<H265FrameHeader>(end);
    return o;
  }
};

inline flatbuffers::Offset<H265FrameHeader> CreateH265FrameHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature = 0,
    bool donlfield = false,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> offsets = 0) {
  H265FrameHeaderBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_codecindex(codecindex);
  builder_.add_offsets(offsets);
  builder_.add_signature(signature);
  builder_.add_donlfield(donlfield);
  builder_.add_marker(marker);
  return builder_.Finish();
}

inline flatbuffers::Offset<H265FrameHeader> CreateH265FrameHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    const std::vector<uint8_t> *signature = nullptr,
    bool donlfield = false,
    const std::vector<uint32_t> *offsets = nullptr) {
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  auto offsets__ = offsets ? _fbb.CreateVector<uint32_t>(*offsets) : 0;
  return file::CreateH265FrameHeader(
      _fbb,
      codecindex,
      offset,
      size,
      marker,
      time,
      signature__,
      donlfield,
      offsets__);
}

struct H264FrameHeader FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODECINDEX = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_MARKER = 10,
    VT_TIME = 12,
    VT_SIGNATURE = 14,
    VT_OFFSETS = 16
  };
  uint64_t codecindex() const {
    return GetField<uint64_t>(VT_CODECINDEX, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  const flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  const flatbuffers::Vector<uint32_t> *offsets() const {
    return GetPointer<const flatbuffers::Vector<uint32_t> *>(VT_OFFSETS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CODECINDEX) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_MARKER) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           VerifyOffset(verifier, VT_OFFSETS) &&
           verifier.VerifyVector(offsets()) &&
           verifier.EndTable();
  }
};

struct H264FrameHeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_codecindex(uint64_t codecindex) {
    fbb_.AddElement<uint64_t>(H264FrameHeader::VT_CODECINDEX, codecindex, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(H264FrameHeader::VT_OFFSET, offset, 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(H264FrameHeader::VT_SIZE, size, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(H264FrameHeader::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(H264FrameHeader::VT_TIME, time, 0);
  }
  void add_signature(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(H264FrameHeader::VT_SIGNATURE, signature);
  }
  void add_offsets(flatbuffers::Offset<flatbuffers::Vector<uint32_t>> offsets) {
    fbb_.AddOffset(H264FrameHeader::VT_OFFSETS, offsets);
  }
  explicit H264FrameHeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  H264FrameHeaderBuilder &operator=(const H264FrameHeaderBuilder &);
  flatbuffers::Offset<H264FrameHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<H264FrameHeader>(end);
    return o;
  }
};

inline flatbuffers::Offset<H264FrameHeader> CreateH264FrameHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint32_t>> offsets = 0) {
  H264FrameHeaderBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_codecindex(codecindex);
  builder_.add_offsets(offsets);
  builder_.add_signature(signature);
  builder_.add_marker(marker);
  return builder_.Finish();
}

inline flatbuffers::Offset<H264FrameHeader> CreateH264FrameHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    const std::vector<uint8_t> *signature = nullptr,
    const std::vector<uint32_t> *offsets = nullptr) {
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  auto offsets__ = offsets ? _fbb.CreateVector<uint32_t>(*offsets) : 0;
  return file::CreateH264FrameHeader(
      _fbb,
      codecindex,
      offset,
      size,
      marker,
      time,
      signature__,
      offsets__);
}

struct JPEGFrameHeader FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODECINDEX = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_MARKER = 10,
    VT_TIME = 12,
    VT_SIGNATURE = 14,
    VT_RESTARTINTERVAL = 16,
    VT_TYPESPECIFICFRAGMENTOFFSET = 18,
    VT_TYPE = 20,
    VT_Q = 22,
    VT_WIDTH = 24,
    VT_HEIGHT = 26,
    VT_LQT = 28,
    VT_CQT = 30
  };
  uint64_t codecindex() const {
    return GetField<uint64_t>(VT_CODECINDEX, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  const flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  uint16_t restartinterval() const {
    return GetField<uint16_t>(VT_RESTARTINTERVAL, 0);
  }
  uint32_t typespecificfragmentoffset() const {
    return GetField<uint32_t>(VT_TYPESPECIFICFRAGMENTOFFSET, 0);
  }
  uint8_t type() const {
    return GetField<uint8_t>(VT_TYPE, 0);
  }
  uint8_t q() const {
    return GetField<uint8_t>(VT_Q, 0);
  }
  uint8_t width() const {
    return GetField<uint8_t>(VT_WIDTH, 0);
  }
  uint8_t height() const {
    return GetField<uint8_t>(VT_HEIGHT, 0);
  }
  const flatbuffers::Vector<uint8_t> *lqt() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_LQT);
  }
  const flatbuffers::Vector<uint8_t> *cqt() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_CQT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CODECINDEX) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_MARKER) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           VerifyField<uint16_t>(verifier, VT_RESTARTINTERVAL) &&
           VerifyField<uint32_t>(verifier, VT_TYPESPECIFICFRAGMENTOFFSET) &&
           VerifyField<uint8_t>(verifier, VT_TYPE) &&
           VerifyField<uint8_t>(verifier, VT_Q) &&
           VerifyField<uint8_t>(verifier, VT_WIDTH) &&
           VerifyField<uint8_t>(verifier, VT_HEIGHT) &&
           VerifyOffset(verifier, VT_LQT) &&
           verifier.VerifyVector(lqt()) &&
           VerifyOffset(verifier, VT_CQT) &&
           verifier.VerifyVector(cqt()) &&
           verifier.EndTable();
  }
};

struct JPEGFrameHeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_codecindex(uint64_t codecindex) {
    fbb_.AddElement<uint64_t>(JPEGFrameHeader::VT_CODECINDEX, codecindex, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(JPEGFrameHeader::VT_OFFSET, offset, 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(JPEGFrameHeader::VT_SIZE, size, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(JPEGFrameHeader::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(JPEGFrameHeader::VT_TIME, time, 0);
  }
  void add_signature(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(JPEGFrameHeader::VT_SIGNATURE, signature);
  }
  void add_restartinterval(uint16_t restartinterval) {
    fbb_.AddElement<uint16_t>(JPEGFrameHeader::VT_RESTARTINTERVAL, restartinterval, 0);
  }
  void add_typespecificfragmentoffset(uint32_t typespecificfragmentoffset) {
    fbb_.AddElement<uint32_t>(JPEGFrameHeader::VT_TYPESPECIFICFRAGMENTOFFSET, typespecificfragmentoffset, 0);
  }
  void add_type(uint8_t type) {
    fbb_.AddElement<uint8_t>(JPEGFrameHeader::VT_TYPE, type, 0);
  }
  void add_q(uint8_t q) {
    fbb_.AddElement<uint8_t>(JPEGFrameHeader::VT_Q, q, 0);
  }
  void add_width(uint8_t width) {
    fbb_.AddElement<uint8_t>(JPEGFrameHeader::VT_WIDTH, width, 0);
  }
  void add_height(uint8_t height) {
    fbb_.AddElement<uint8_t>(JPEGFrameHeader::VT_HEIGHT, height, 0);
  }
  void add_lqt(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> lqt) {
    fbb_.AddOffset(JPEGFrameHeader::VT_LQT, lqt);
  }
  void add_cqt(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> cqt) {
    fbb_.AddOffset(JPEGFrameHeader::VT_CQT, cqt);
  }
  explicit JPEGFrameHeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  JPEGFrameHeaderBuilder &operator=(const JPEGFrameHeaderBuilder &);
  flatbuffers::Offset<JPEGFrameHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<JPEGFrameHeader>(end);
    return o;
  }
};

inline flatbuffers::Offset<JPEGFrameHeader> CreateJPEGFrameHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature = 0,
    uint16_t restartinterval = 0,
    uint32_t typespecificfragmentoffset = 0,
    uint8_t type = 0,
    uint8_t q = 0,
    uint8_t width = 0,
    uint8_t height = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> lqt = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> cqt = 0) {
  JPEGFrameHeaderBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_codecindex(codecindex);
  builder_.add_cqt(cqt);
  builder_.add_lqt(lqt);
  builder_.add_typespecificfragmentoffset(typespecificfragmentoffset);
  builder_.add_signature(signature);
  builder_.add_restartinterval(restartinterval);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_q(q);
  builder_.add_type(type);
  builder_.add_marker(marker);
  return builder_.Finish();
}

inline flatbuffers::Offset<JPEGFrameHeader> CreateJPEGFrameHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    const std::vector<uint8_t> *signature = nullptr,
    uint16_t restartinterval = 0,
    uint32_t typespecificfragmentoffset = 0,
    uint8_t type = 0,
    uint8_t q = 0,
    uint8_t width = 0,
    uint8_t height = 0,
    const std::vector<uint8_t> *lqt = nullptr,
    const std::vector<uint8_t> *cqt = nullptr) {
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  auto lqt__ = lqt ? _fbb.CreateVector<uint8_t>(*lqt) : 0;
  auto cqt__ = cqt ? _fbb.CreateVector<uint8_t>(*cqt) : 0;
  return file::CreateJPEGFrameHeader(
      _fbb,
      codecindex,
      offset,
      size,
      marker,
      time,
      signature__,
      restartinterval,
      typespecificfragmentoffset,
      type,
      q,
      width,
      height,
      lqt__,
      cqt__);
}

struct MetadataFrameHeader FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODECINDEX = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_MARKER = 10,
    VT_TIME = 12,
    VT_SIGNATURE = 14
  };
  uint64_t codecindex() const {
    return GetField<uint64_t>(VT_CODECINDEX, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  const flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CODECINDEX) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_MARKER) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           verifier.EndTable();
  }
};

struct MetadataFrameHeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_codecindex(uint64_t codecindex) {
    fbb_.AddElement<uint64_t>(MetadataFrameHeader::VT_CODECINDEX, codecindex, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(MetadataFrameHeader::VT_OFFSET, offset, 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(MetadataFrameHeader::VT_SIZE, size, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(MetadataFrameHeader::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(MetadataFrameHeader::VT_TIME, time, 0);
  }
  void add_signature(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(MetadataFrameHeader::VT_SIGNATURE, signature);
  }
  explicit MetadataFrameHeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MetadataFrameHeaderBuilder &operator=(const MetadataFrameHeaderBuilder &);
  flatbuffers::Offset<MetadataFrameHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MetadataFrameHeader>(end);
    return o;
  }
};

inline flatbuffers::Offset<MetadataFrameHeader> CreateMetadataFrameHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature = 0) {
  MetadataFrameHeaderBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_codecindex(codecindex);
  builder_.add_signature(signature);
  builder_.add_marker(marker);
  return builder_.Finish();
}

inline flatbuffers::Offset<MetadataFrameHeader> CreateMetadataFrameHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    const std::vector<uint8_t> *signature = nullptr) {
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  return file::CreateMetadataFrameHeader(
      _fbb,
      codecindex,
      offset,
      size,
      marker,
      time,
      signature__);
}

struct MPEG4FrameHeader FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODECINDEX = 4,
    VT_OFFSET = 6,
    VT_SIZE = 8,
    VT_MARKER = 10,
    VT_TIME = 12,
    VT_SIGNATURE = 14
  };
  uint64_t codecindex() const {
    return GetField<uint64_t>(VT_CODECINDEX, 0);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  uint64_t size() const {
    return GetField<uint64_t>(VT_SIZE, 0);
  }
  bool marker() const {
    return GetField<uint8_t>(VT_MARKER, 0) != 0;
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  const flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_CODECINDEX) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET) &&
           VerifyField<uint64_t>(verifier, VT_SIZE) &&
           VerifyField<uint8_t>(verifier, VT_MARKER) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           verifier.EndTable();
  }
};

struct MPEG4FrameHeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_codecindex(uint64_t codecindex) {
    fbb_.AddElement<uint64_t>(MPEG4FrameHeader::VT_CODECINDEX, codecindex, 0);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(MPEG4FrameHeader::VT_OFFSET, offset, 0);
  }
  void add_size(uint64_t size) {
    fbb_.AddElement<uint64_t>(MPEG4FrameHeader::VT_SIZE, size, 0);
  }
  void add_marker(bool marker) {
    fbb_.AddElement<uint8_t>(MPEG4FrameHeader::VT_MARKER, static_cast<uint8_t>(marker), 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(MPEG4FrameHeader::VT_TIME, time, 0);
  }
  void add_signature(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(MPEG4FrameHeader::VT_SIGNATURE, signature);
  }
  explicit MPEG4FrameHeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MPEG4FrameHeaderBuilder &operator=(const MPEG4FrameHeaderBuilder &);
  flatbuffers::Offset<MPEG4FrameHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MPEG4FrameHeader>(end);
    return o;
  }
};

inline flatbuffers::Offset<MPEG4FrameHeader> CreateMPEG4FrameHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> signature = 0) {
  MPEG4FrameHeaderBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_codecindex(codecindex);
  builder_.add_signature(signature);
  builder_.add_marker(marker);
  return builder_.Finish();
}

inline flatbuffers::Offset<MPEG4FrameHeader> CreateMPEG4FrameHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t codecindex = 0,
    uint64_t offset = 0,
    uint64_t size = 0,
    bool marker = false,
    uint64_t time = 0,
    const std::vector<uint8_t> *signature = nullptr) {
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  return file::CreateMPEG4FrameHeader(
      _fbb,
      codecindex,
      offset,
      size,
      marker,
      time,
      signature__);
}

struct Track FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_DESCRIPTION = 6,
    VT_CODECS = 8,
    VT_H264FRAMEHEADERS = 10,
    VT_JPEGFRAMEHEADERS = 12,
    VT_METADATAFRAMEHEADERS = 14,
    VT_MPEG4FRAMEHEADERS = 16,
    VT_H265FRAMEHEADERS = 18
  };
  uint64_t index() const {
    return GetField<uint64_t>(VT_INDEX, 0);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::Codec>> *codecs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::Codec>> *>(VT_CODECS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::H264FrameHeader>> *h264frameheaders() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::H264FrameHeader>> *>(VT_H264FRAMEHEADERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::JPEGFrameHeader>> *jpegframeheaders() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::JPEGFrameHeader>> *>(VT_JPEGFRAMEHEADERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::MetadataFrameHeader>> *metadataframeheaders() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::MetadataFrameHeader>> *>(VT_METADATAFRAMEHEADERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::MPEG4FrameHeader>> *mpeg4frameheaders() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::MPEG4FrameHeader>> *>(VT_MPEG4FRAMEHEADERS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::H265FrameHeader>> *h265frameheaders() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::H265FrameHeader>> *>(VT_H265FRAMEHEADERS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INDEX) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_CODECS) &&
           verifier.VerifyVector(codecs()) &&
           verifier.VerifyVectorOfTables(codecs()) &&
           VerifyOffset(verifier, VT_H264FRAMEHEADERS) &&
           verifier.VerifyVector(h264frameheaders()) &&
           verifier.VerifyVectorOfTables(h264frameheaders()) &&
           VerifyOffset(verifier, VT_JPEGFRAMEHEADERS) &&
           verifier.VerifyVector(jpegframeheaders()) &&
           verifier.VerifyVectorOfTables(jpegframeheaders()) &&
           VerifyOffset(verifier, VT_METADATAFRAMEHEADERS) &&
           verifier.VerifyVector(metadataframeheaders()) &&
           verifier.VerifyVectorOfTables(metadataframeheaders()) &&
           VerifyOffset(verifier, VT_MPEG4FRAMEHEADERS) &&
           verifier.VerifyVector(mpeg4frameheaders()) &&
           verifier.VerifyVectorOfTables(mpeg4frameheaders()) &&
           VerifyOffset(verifier, VT_H265FRAMEHEADERS) &&
           verifier.VerifyVector(h265frameheaders()) &&
           verifier.VerifyVectorOfTables(h265frameheaders()) &&
           verifier.EndTable();
  }
};

struct TrackBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_index(uint64_t index) {
    fbb_.AddElement<uint64_t>(Track::VT_INDEX, index, 0);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(Track::VT_DESCRIPTION, description);
  }
  void add_codecs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Codec>>> codecs) {
    fbb_.AddOffset(Track::VT_CODECS, codecs);
  }
  void add_h264frameheaders(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::H264FrameHeader>>> h264frameheaders) {
    fbb_.AddOffset(Track::VT_H264FRAMEHEADERS, h264frameheaders);
  }
  void add_jpegframeheaders(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::JPEGFrameHeader>>> jpegframeheaders) {
    fbb_.AddOffset(Track::VT_JPEGFRAMEHEADERS, jpegframeheaders);
  }
  void add_metadataframeheaders(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::MetadataFrameHeader>>> metadataframeheaders) {
    fbb_.AddOffset(Track::VT_METADATAFRAMEHEADERS, metadataframeheaders);
  }
  void add_mpeg4frameheaders(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::MPEG4FrameHeader>>> mpeg4frameheaders) {
    fbb_.AddOffset(Track::VT_MPEG4FRAMEHEADERS, mpeg4frameheaders);
  }
  void add_h265frameheaders(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::H265FrameHeader>>> h265frameheaders) {
    fbb_.AddOffset(Track::VT_H265FRAMEHEADERS, h265frameheaders);
  }
  explicit TrackBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TrackBuilder &operator=(const TrackBuilder &);
  flatbuffers::Offset<Track> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Track>(end);
    return o;
  }
};

inline flatbuffers::Offset<Track> CreateTrack(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Codec>>> codecs = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::H264FrameHeader>>> h264frameheaders = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::JPEGFrameHeader>>> jpegframeheaders = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::MetadataFrameHeader>>> metadataframeheaders = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::MPEG4FrameHeader>>> mpeg4frameheaders = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::H265FrameHeader>>> h265frameheaders = 0) {
  TrackBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_h265frameheaders(h265frameheaders);
  builder_.add_mpeg4frameheaders(mpeg4frameheaders);
  builder_.add_metadataframeheaders(metadataframeheaders);
  builder_.add_jpegframeheaders(jpegframeheaders);
  builder_.add_h264frameheaders(h264frameheaders);
  builder_.add_codecs(codecs);
  builder_.add_description(description);
  return builder_.Finish();
}

inline flatbuffers::Offset<Track> CreateTrackDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    const char *description = nullptr,
    const std::vector<flatbuffers::Offset<file::Codec>> *codecs = nullptr,
    const std::vector<flatbuffers::Offset<file::H264FrameHeader>> *h264frameheaders = nullptr,
    const std::vector<flatbuffers::Offset<file::JPEGFrameHeader>> *jpegframeheaders = nullptr,
    const std::vector<flatbuffers::Offset<file::MetadataFrameHeader>> *metadataframeheaders = nullptr,
    const std::vector<flatbuffers::Offset<file::MPEG4FrameHeader>> *mpeg4frameheaders = nullptr,
    const std::vector<flatbuffers::Offset<file::H265FrameHeader>> *h265frameheaders = nullptr) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto codecs__ = codecs ? _fbb.CreateVector<flatbuffers::Offset<file::Codec>>(*codecs) : 0;
  auto h264frameheaders__ = h264frameheaders ? _fbb.CreateVector<flatbuffers::Offset<file::H264FrameHeader>>(*h264frameheaders) : 0;
  auto jpegframeheaders__ = jpegframeheaders ? _fbb.CreateVector<flatbuffers::Offset<file::JPEGFrameHeader>>(*jpegframeheaders) : 0;
  auto metadataframeheaders__ = metadataframeheaders ? _fbb.CreateVector<flatbuffers::Offset<file::MetadataFrameHeader>>(*metadataframeheaders) : 0;
  auto mpeg4frameheaders__ = mpeg4frameheaders ? _fbb.CreateVector<flatbuffers::Offset<file::MPEG4FrameHeader>>(*mpeg4frameheaders) : 0;
  auto h265frameheaders__ = h265frameheaders ? _fbb.CreateVector<flatbuffers::Offset<file::H265FrameHeader>>(*h265frameheaders) : 0;
  return file::CreateTrack(
      _fbb,
      index,
      description__,
      codecs__,
      h264frameheaders__,
      jpegframeheaders__,
      metadataframeheaders__,
      mpeg4frameheaders__,
      h265frameheaders__);
}

struct Recording FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_NAME = 6,
    VT_TRACKS = 8,
    VT_LOCATION = 10
  };
  uint64_t index() const {
    return GetField<uint64_t>(VT_INDEX, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::Track>> *tracks() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::Track>> *>(VT_TRACKS);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INDEX) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TRACKS) &&
           verifier.VerifyVector(tracks()) &&
           verifier.VerifyVectorOfTables(tracks()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           verifier.EndTable();
  }
};

struct RecordingBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_index(uint64_t index) {
    fbb_.AddElement<uint64_t>(Recording::VT_INDEX, index, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Recording::VT_NAME, name);
  }
  void add_tracks(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Track>>> tracks) {
    fbb_.AddOffset(Recording::VT_TRACKS, tracks);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(Recording::VT_LOCATION, location);
  }
  explicit RecordingBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  RecordingBuilder &operator=(const RecordingBuilder &);
  flatbuffers::Offset<Recording> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Recording>(end);
    return o;
  }
};

inline flatbuffers::Offset<Recording> CreateRecording(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Track>>> tracks = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0) {
  RecordingBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_location(location);
  builder_.add_tracks(tracks);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Recording> CreateRecordingDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    const char *name = nullptr,
    const std::vector<flatbuffers::Offset<file::Track>> *tracks = nullptr,
    const char *location = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto tracks__ = tracks ? _fbb.CreateVector<flatbuffers::Offset<file::Track>>(*tracks) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  return file::CreateRecording(
      _fbb,
      index,
      name__,
      tracks__,
      location__);
}

struct Device FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDEX = 4,
    VT_NAME = 6,
    VT_ADDRESS = 8,
    VT_SIGNINGKEY = 10,
    VT_RECORDINGS = 12
  };
  uint64_t index() const {
    return GetField<uint64_t>(VT_INDEX, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *address() const {
    return GetPointer<const flatbuffers::String *>(VT_ADDRESS);
  }
  const flatbuffers::String *signingkey() const {
    return GetPointer<const flatbuffers::String *>(VT_SIGNINGKEY);
  }
  const flatbuffers::Vector<flatbuffers::Offset<file::Recording>> *recordings() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::Recording>> *>(VT_RECORDINGS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_INDEX) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_ADDRESS) &&
           verifier.VerifyString(address()) &&
           VerifyOffset(verifier, VT_SIGNINGKEY) &&
           verifier.VerifyString(signingkey()) &&
           VerifyOffset(verifier, VT_RECORDINGS) &&
           verifier.VerifyVector(recordings()) &&
           verifier.VerifyVectorOfTables(recordings()) &&
           verifier.EndTable();
  }
};

struct DeviceBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_index(uint64_t index) {
    fbb_.AddElement<uint64_t>(Device::VT_INDEX, index, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Device::VT_NAME, name);
  }
  void add_address(flatbuffers::Offset<flatbuffers::String> address) {
    fbb_.AddOffset(Device::VT_ADDRESS, address);
  }
  void add_signingkey(flatbuffers::Offset<flatbuffers::String> signingkey) {
    fbb_.AddOffset(Device::VT_SIGNINGKEY, signingkey);
  }
  void add_recordings(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Recording>>> recordings) {
    fbb_.AddOffset(Device::VT_RECORDINGS, recordings);
  }
  explicit DeviceBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  DeviceBuilder &operator=(const DeviceBuilder &);
  flatbuffers::Offset<Device> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Device>(end);
    return o;
  }
};

inline flatbuffers::Offset<Device> CreateDevice(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> address = 0,
    flatbuffers::Offset<flatbuffers::String> signingkey = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Recording>>> recordings = 0) {
  DeviceBuilder builder_(_fbb);
  builder_.add_index(index);
  builder_.add_recordings(recordings);
  builder_.add_signingkey(signingkey);
  builder_.add_address(address);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Device> CreateDeviceDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t index = 0,
    const char *name = nullptr,
    const char *address = nullptr,
    const char *signingkey = nullptr,
    const std::vector<flatbuffers::Offset<file::Recording>> *recordings = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto address__ = address ? _fbb.CreateString(address) : 0;
  auto signingkey__ = signingkey ? _fbb.CreateString(signingkey) : 0;
  auto recordings__ = recordings ? _fbb.CreateVector<flatbuffers::Offset<file::Recording>>(*recordings) : 0;
  return file::CreateDevice(
      _fbb,
      index,
      name__,
      address__,
      signingkey__,
      recordings__);
}

struct File FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DEVICES = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<file::Device>> *devices() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<file::Device>> *>(VT_DEVICES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DEVICES) &&
           verifier.VerifyVector(devices()) &&
           verifier.VerifyVectorOfTables(devices()) &&
           verifier.EndTable();
  }
};

struct FileBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_devices(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Device>>> devices) {
    fbb_.AddOffset(File::VT_DEVICES, devices);
  }
  explicit FileBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FileBuilder &operator=(const FileBuilder &);
  flatbuffers::Offset<File> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<File>(end);
    return o;
  }
};

inline flatbuffers::Offset<File> CreateFile(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<file::Device>>> devices = 0) {
  FileBuilder builder_(_fbb);
  builder_.add_devices(devices);
  return builder_.Finish();
}

inline flatbuffers::Offset<File> CreateFileDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<file::Device>> *devices = nullptr) {
  auto devices__ = devices ? _fbb.CreateVector<flatbuffers::Offset<file::Device>>(*devices) : 0;
  return file::CreateFile(
      _fbb,
      devices__);
}

inline const file::File *GetFile(const void *buf) {
  return flatbuffers::GetRoot<file::File>(buf);
}

inline const file::File *GetSizePrefixedFile(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<file::File>(buf);
}

inline bool VerifyFileBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<file::File>(nullptr);
}

inline bool VerifySizePrefixedFileBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<file::File>(nullptr);
}

inline void FinishFileBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<file::File> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFileBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<file::File> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace file

#endif  // FLATBUFFERS_GENERATED_FILE_FILE_H_
