// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ADDMAPREQUEST_MONOCLE_H_
#define FLATBUFFERS_GENERATED_ADDMAPREQUEST_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct AddMapRequest;

struct AddMapRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_LOCATION = 6,
    VT_IMAGE = 8
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  const flatbuffers::Vector<int8_t> *image() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_IMAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_IMAGE) &&
           verifier.VerifyVector(image()) &&
           verifier.EndTable();
  }
};

struct AddMapRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(AddMapRequest::VT_NAME, name);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(AddMapRequest::VT_LOCATION, location);
  }
  void add_image(flatbuffers::Offset<flatbuffers::Vector<int8_t>> image) {
    fbb_.AddOffset(AddMapRequest::VT_IMAGE, image);
  }
  explicit AddMapRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AddMapRequestBuilder &operator=(const AddMapRequestBuilder &);
  flatbuffers::Offset<AddMapRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AddMapRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<AddMapRequest> CreateAddMapRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> image = 0) {
  AddMapRequestBuilder builder_(_fbb);
  builder_.add_image(image);
  builder_.add_location(location);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<AddMapRequest> CreateAddMapRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *location = nullptr,
    const std::vector<int8_t> *image = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto image__ = image ? _fbb.CreateVector<int8_t>(*image) : 0;
  return monocle::CreateAddMapRequest(
      _fbb,
      name__,
      location__,
      image__);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_ADDMAPREQUEST_MONOCLE_H_
