// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ADDRECORDINGREQUEST_MONOCLE_H_
#define FLATBUFFERS_GENERATED_ADDRECORDINGREQUEST_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct AddRecordingRequest;
struct AddRecordingRequestBuilder;

struct AddRecordingRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AddRecordingRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCEID = 4,
    VT_NAME = 6,
    VT_LOCATION = 8,
    VT_DESCRIPTION = 10,
    VT_ADDRESS = 12,
    VT_CONTENT = 14,
    VT_RETENTIONTIME = 16,
    VT_CREATEDEFAULTTRACKS = 18,
    VT_CREATEDEFAULTJOB = 20,
    VT_ADAPTIVESTREAMING = 22
  };
  const flatbuffers::String *sourceid() const {
    return GetPointer<const flatbuffers::String *>(VT_SOURCEID);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  const flatbuffers::String *description() const {
    return GetPointer<const flatbuffers::String *>(VT_DESCRIPTION);
  }
  const flatbuffers::String *address() const {
    return GetPointer<const flatbuffers::String *>(VT_ADDRESS);
  }
  const flatbuffers::String *content() const {
    return GetPointer<const flatbuffers::String *>(VT_CONTENT);
  }
  uint64_t retentiontime() const {
    return GetField<uint64_t>(VT_RETENTIONTIME, 0);
  }
  bool createdefaulttracks() const {
    return GetField<uint8_t>(VT_CREATEDEFAULTTRACKS, 0) != 0;
  }
  bool createdefaultjob() const {
    return GetField<uint8_t>(VT_CREATEDEFAULTJOB, 0) != 0;
  }
  bool adaptivestreaming() const {
    return GetField<uint8_t>(VT_ADAPTIVESTREAMING, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SOURCEID) &&
           verifier.VerifyString(sourceid()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_ADDRESS) &&
           verifier.VerifyString(address()) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           verifier.VerifyString(content()) &&
           VerifyField<uint64_t>(verifier, VT_RETENTIONTIME) &&
           VerifyField<uint8_t>(verifier, VT_CREATEDEFAULTTRACKS) &&
           VerifyField<uint8_t>(verifier, VT_CREATEDEFAULTJOB) &&
           VerifyField<uint8_t>(verifier, VT_ADAPTIVESTREAMING) &&
           verifier.EndTable();
  }
};

struct AddRecordingRequestBuilder {
  typedef AddRecordingRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_sourceid(flatbuffers::Offset<flatbuffers::String> sourceid) {
    fbb_.AddOffset(AddRecordingRequest::VT_SOURCEID, sourceid);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(AddRecordingRequest::VT_NAME, name);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(AddRecordingRequest::VT_LOCATION, location);
  }
  void add_description(flatbuffers::Offset<flatbuffers::String> description) {
    fbb_.AddOffset(AddRecordingRequest::VT_DESCRIPTION, description);
  }
  void add_address(flatbuffers::Offset<flatbuffers::String> address) {
    fbb_.AddOffset(AddRecordingRequest::VT_ADDRESS, address);
  }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) {
    fbb_.AddOffset(AddRecordingRequest::VT_CONTENT, content);
  }
  void add_retentiontime(uint64_t retentiontime) {
    fbb_.AddElement<uint64_t>(AddRecordingRequest::VT_RETENTIONTIME, retentiontime, 0);
  }
  void add_createdefaulttracks(bool createdefaulttracks) {
    fbb_.AddElement<uint8_t>(AddRecordingRequest::VT_CREATEDEFAULTTRACKS, static_cast<uint8_t>(createdefaulttracks), 0);
  }
  void add_createdefaultjob(bool createdefaultjob) {
    fbb_.AddElement<uint8_t>(AddRecordingRequest::VT_CREATEDEFAULTJOB, static_cast<uint8_t>(createdefaultjob), 0);
  }
  void add_adaptivestreaming(bool adaptivestreaming) {
    fbb_.AddElement<uint8_t>(AddRecordingRequest::VT_ADAPTIVESTREAMING, static_cast<uint8_t>(adaptivestreaming), 0);
  }
  explicit AddRecordingRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AddRecordingRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AddRecordingRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<AddRecordingRequest> CreateAddRecordingRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> sourceid = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0,
    flatbuffers::Offset<flatbuffers::String> description = 0,
    flatbuffers::Offset<flatbuffers::String> address = 0,
    flatbuffers::Offset<flatbuffers::String> content = 0,
    uint64_t retentiontime = 0,
    bool createdefaulttracks = false,
    bool createdefaultjob = false,
    bool adaptivestreaming = false) {
  AddRecordingRequestBuilder builder_(_fbb);
  builder_.add_retentiontime(retentiontime);
  builder_.add_content(content);
  builder_.add_address(address);
  builder_.add_description(description);
  builder_.add_location(location);
  builder_.add_name(name);
  builder_.add_sourceid(sourceid);
  builder_.add_adaptivestreaming(adaptivestreaming);
  builder_.add_createdefaultjob(createdefaultjob);
  builder_.add_createdefaulttracks(createdefaulttracks);
  return builder_.Finish();
}

inline flatbuffers::Offset<AddRecordingRequest> CreateAddRecordingRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *sourceid = nullptr,
    const char *name = nullptr,
    const char *location = nullptr,
    const char *description = nullptr,
    const char *address = nullptr,
    const char *content = nullptr,
    uint64_t retentiontime = 0,
    bool createdefaulttracks = false,
    bool createdefaultjob = false,
    bool adaptivestreaming = false) {
  auto sourceid__ = sourceid ? _fbb.CreateString(sourceid) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto address__ = address ? _fbb.CreateString(address) : 0;
  auto content__ = content ? _fbb.CreateString(content) : 0;
  return monocle::CreateAddRecordingRequest(
      _fbb,
      sourceid__,
      name__,
      location__,
      description__,
      address__,
      content__,
      retentiontime,
      createdefaulttracks,
      createdefaultjob,
      adaptivestreaming);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_ADDRECORDINGREQUEST_MONOCLE_H_
