// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ADDRECORDINGJOBRESPONSE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_ADDRECORDINGJOBRESPONSE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct AddRecordingJobResponse;

struct AddRecordingJobResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORDINGJOBTOKEN = 4
  };
  uint64_t recordingjobtoken() const {
    return GetField<uint64_t>(VT_RECORDINGJOBTOKEN, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_RECORDINGJOBTOKEN) &&
           verifier.EndTable();
  }
};

struct AddRecordingJobResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_recordingjobtoken(uint64_t recordingjobtoken) {
    fbb_.AddElement<uint64_t>(AddRecordingJobResponse::VT_RECORDINGJOBTOKEN, recordingjobtoken, 0);
  }
  explicit AddRecordingJobResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AddRecordingJobResponseBuilder &operator=(const AddRecordingJobResponseBuilder &);
  flatbuffers::Offset<AddRecordingJobResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AddRecordingJobResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<AddRecordingJobResponse> CreateAddRecordingJobResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t recordingjobtoken = 0) {
  AddRecordingJobResponseBuilder builder_(_fbb);
  builder_.add_recordingjobtoken(recordingjobtoken);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_ADDRECORDINGJOBRESPONSE_MONOCLE_H_
