// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_AUTHENTICATERESPONSE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_AUTHENTICATERESPONSE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct AuthenticateResponse;
struct AuthenticateResponseBuilder;

struct AuthenticateResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AuthenticateResponseBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct AuthenticateResponseBuilder {
  typedef AuthenticateResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit AuthenticateResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<AuthenticateResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AuthenticateResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<AuthenticateResponse> CreateAuthenticateResponse(
    flatbuffers::FlatBufferBuilder &_fbb) {
  AuthenticateResponseBuilder builder_(_fbb);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_AUTHENTICATERESPONSE_MONOCLE_H_
