// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CHANGEUSERREQUEST_MONOCLE_H_
#define FLATBUFFERS_GENERATED_CHANGEUSERREQUEST_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct ChangeUserRequest;
struct ChangeUserRequestBuilder;

struct ChangeUserRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ChangeUserRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_DIGEST = 6,
    VT_GROUP = 8
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  const flatbuffers::String *digest() const {
    return GetPointer<const flatbuffers::String *>(VT_DIGEST);
  }
  uint64_t group() const {
    return GetField<uint64_t>(VT_GROUP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyOffset(verifier, VT_DIGEST) &&
           verifier.VerifyString(digest()) &&
           VerifyField<uint64_t>(verifier, VT_GROUP) &&
           verifier.EndTable();
  }
};

struct ChangeUserRequestBuilder {
  typedef ChangeUserRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(ChangeUserRequest::VT_TOKEN, token, 0);
  }
  void add_digest(flatbuffers::Offset<flatbuffers::String> digest) {
    fbb_.AddOffset(ChangeUserRequest::VT_DIGEST, digest);
  }
  void add_group(uint64_t group) {
    fbb_.AddElement<uint64_t>(ChangeUserRequest::VT_GROUP, group, 0);
  }
  explicit ChangeUserRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ChangeUserRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ChangeUserRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<ChangeUserRequest> CreateChangeUserRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    flatbuffers::Offset<flatbuffers::String> digest = 0,
    uint64_t group = 0) {
  ChangeUserRequestBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_token(token);
  builder_.add_digest(digest);
  return builder_.Finish();
}

inline flatbuffers::Offset<ChangeUserRequest> CreateChangeUserRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    const char *digest = nullptr,
    uint64_t group = 0) {
  auto digest__ = digest ? _fbb.CreateString(digest) : 0;
  return monocle::CreateChangeUserRequest(
      _fbb,
      token,
      digest__,
      group);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_CHANGEUSERREQUEST_MONOCLE_H_
