// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONTROLSTREAMPAUSEREQUEST_MONOCLE_H_
#define FLATBUFFERS_GENERATED_CONTROLSTREAMPAUSEREQUEST_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct ControlStreamPauseRequest;
struct ControlStreamPauseRequestBuilder;

struct ControlStreamPauseRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ControlStreamPauseRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_TIME = 6
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  uint64_t time() const {
    return GetField<uint64_t>(VT_TIME, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyField<uint64_t>(verifier, VT_TIME) &&
           verifier.EndTable();
  }
};

struct ControlStreamPauseRequestBuilder {
  typedef ControlStreamPauseRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(ControlStreamPauseRequest::VT_TOKEN, token, 0);
  }
  void add_time(uint64_t time) {
    fbb_.AddElement<uint64_t>(ControlStreamPauseRequest::VT_TIME, time, 0);
  }
  explicit ControlStreamPauseRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ControlStreamPauseRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ControlStreamPauseRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<ControlStreamPauseRequest> CreateControlStreamPauseRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    uint64_t time = 0) {
  ControlStreamPauseRequestBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_token(token);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_CONTROLSTREAMPAUSEREQUEST_MONOCLE_H_
