// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FILEMONITORSTATE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_FILEMONITORSTATE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class FileMonitorState : int8_t {
  Unavailable = 0,
  Available = 1,
  MIN = Unavailable,
  MAX = Available
};

inline const FileMonitorState (&EnumValuesFileMonitorState())[2] {
  static const FileMonitorState values[] = {
    FileMonitorState::Unavailable,
    FileMonitorState::Available
  };
  return values;
}

inline const char * const *EnumNamesFileMonitorState() {
  static const char * const names[] = {
    "Unavailable",
    "Available",
    nullptr
  };
  return names;
}

inline const char *EnumNameFileMonitorState(FileMonitorState e) {
  if (e < FileMonitorState::Unavailable || e > FileMonitorState::Available) return "";
  const size_t index = static_cast<int>(e);
  return EnumNamesFileMonitorState()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_FILEMONITORSTATE_MONOCLE_H_
