// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FINDMOTIONRESULT_MONOCLE_H_
#define FLATBUFFERS_GENERATED_FINDMOTIONRESULT_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct FindMotionResult;

struct FindMotionResult FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_START = 6,
    VT_END = 8
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  uint64_t start() const {
    return GetField<uint64_t>(VT_START, 0);
  }
  uint64_t end() const {
    return GetField<uint64_t>(VT_END, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyField<uint64_t>(verifier, VT_START) &&
           VerifyField<uint64_t>(verifier, VT_END) &&
           verifier.EndTable();
  }
};

struct FindMotionResultBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(FindMotionResult::VT_TOKEN, token, 0);
  }
  void add_start(uint64_t start) {
    fbb_.AddElement<uint64_t>(FindMotionResult::VT_START, start, 0);
  }
  void add_end(uint64_t end) {
    fbb_.AddElement<uint64_t>(FindMotionResult::VT_END, end, 0);
  }
  explicit FindMotionResultBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FindMotionResultBuilder &operator=(const FindMotionResultBuilder &);
  flatbuffers::Offset<FindMotionResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FindMotionResult>(end);
    return o;
  }
};

inline flatbuffers::Offset<FindMotionResult> CreateFindMotionResult(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    uint64_t start = 0,
    uint64_t end = 0) {
  FindMotionResultBuilder builder_(_fbb);
  builder_.add_end(end);
  builder_.add_start(start);
  builder_.add_token(token);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_FINDMOTIONRESULT_MONOCLE_H_
