// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FINDMOTIONPROGRESS_MONOCLE_H_
#define FLATBUFFERS_GENERATED_FINDMOTIONPROGRESS_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct FindMotionProgress;

struct FindMotionProgress FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_PROGRESS = 6
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  float progress() const {
    return GetField<float>(VT_PROGRESS, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyField<float>(verifier, VT_PROGRESS) &&
           verifier.EndTable();
  }
};

struct FindMotionProgressBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(FindMotionProgress::VT_TOKEN, token, 0);
  }
  void add_progress(float progress) {
    fbb_.AddElement<float>(FindMotionProgress::VT_PROGRESS, progress, 0.0f);
  }
  explicit FindMotionProgressBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  FindMotionProgressBuilder &operator=(const FindMotionProgressBuilder &);
  flatbuffers::Offset<FindMotionProgress> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FindMotionProgress>(end);
    return o;
  }
};

inline flatbuffers::Offset<FindMotionProgress> CreateFindMotionProgress(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    float progress = 0.0f) {
  FindMotionProgressBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_progress(progress);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_FINDMOTIONPROGRESS_MONOCLE_H_
