// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LAYOUTADDED_MONOCLE_H_
#define FLATBUFFERS_GENERATED_LAYOUTADDED_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

#include "layout_generated.h"

namespace monocle {

struct LayoutAdded;

struct LayoutAdded FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LAYOUT = 4
  };
  const monocle::Layout *layout() const {
    return GetPointer<const monocle::Layout *>(VT_LAYOUT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LAYOUT) &&
           verifier.VerifyTable(layout()) &&
           verifier.EndTable();
  }
};

struct LayoutAddedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_layout(flatbuffers::Offset<monocle::Layout> layout) {
    fbb_.AddOffset(LayoutAdded::VT_LAYOUT, layout);
  }
  explicit LayoutAddedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LayoutAddedBuilder &operator=(const LayoutAddedBuilder &);
  flatbuffers::Offset<LayoutAdded> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LayoutAdded>(end);
    return o;
  }
};

inline flatbuffers::Offset<LayoutAdded> CreateLayoutAdded(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<monocle::Layout> layout = 0) {
  LayoutAddedBuilder builder_(_fbb);
  builder_.add_layout(layout);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_LAYOUTADDED_MONOCLE_H_
