// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAP_MONOCLE_H_
#define FLATBUFFERS_GENERATED_MAP_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct Map;
struct MapBuilder;

struct Map FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_NAME = 6,
    VT_LOCATION = 8,
    VT_MD5SUM = 10,
    VT_GUIORDER = 12
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  const flatbuffers::String *md5sum() const {
    return GetPointer<const flatbuffers::String *>(VT_MD5SUM);
  }
  uint64_t guiorder() const {
    return GetField<uint64_t>(VT_GUIORDER, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_MD5SUM) &&
           verifier.VerifyString(md5sum()) &&
           VerifyField<uint64_t>(verifier, VT_GUIORDER) &&
           verifier.EndTable();
  }
};

struct MapBuilder {
  typedef Map Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(Map::VT_TOKEN, token, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Map::VT_NAME, name);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(Map::VT_LOCATION, location);
  }
  void add_md5sum(flatbuffers::Offset<flatbuffers::String> md5sum) {
    fbb_.AddOffset(Map::VT_MD5SUM, md5sum);
  }
  void add_guiorder(uint64_t guiorder) {
    fbb_.AddElement<uint64_t>(Map::VT_GUIORDER, guiorder, 0);
  }
  explicit MapBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Map> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Map>(end);
    return o;
  }
};

inline flatbuffers::Offset<Map> CreateMap(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0,
    flatbuffers::Offset<flatbuffers::String> md5sum = 0,
    uint64_t guiorder = 0) {
  MapBuilder builder_(_fbb);
  builder_.add_guiorder(guiorder);
  builder_.add_token(token);
  builder_.add_md5sum(md5sum);
  builder_.add_location(location);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Map> CreateMapDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    const char *name = nullptr,
    const char *location = nullptr,
    const char *md5sum = nullptr,
    uint64_t guiorder = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto md5sum__ = md5sum ? _fbb.CreateString(md5sum) : 0;
  return monocle::CreateMap(
      _fbb,
      token,
      name__,
      location__,
      md5sum__,
      guiorder);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_MAP_MONOCLE_H_
