// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAPCHANGED_MONOCLE_H_
#define FLATBUFFERS_GENERATED_MAPCHANGED_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct MapChanged;

struct MapChanged FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_NAME = 6,
    VT_LOCATION = 8,
    VT_IMAGEMD5 = 10
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *location() const {
    return GetPointer<const flatbuffers::String *>(VT_LOCATION);
  }
  const flatbuffers::String *imagemd5() const {
    return GetPointer<const flatbuffers::String *>(VT_IMAGEMD5);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyString(location()) &&
           VerifyOffset(verifier, VT_IMAGEMD5) &&
           verifier.VerifyString(imagemd5()) &&
           verifier.EndTable();
  }
};

struct MapChangedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(MapChanged::VT_TOKEN, token, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(MapChanged::VT_NAME, name);
  }
  void add_location(flatbuffers::Offset<flatbuffers::String> location) {
    fbb_.AddOffset(MapChanged::VT_LOCATION, location);
  }
  void add_imagemd5(flatbuffers::Offset<flatbuffers::String> imagemd5) {
    fbb_.AddOffset(MapChanged::VT_IMAGEMD5, imagemd5);
  }
  explicit MapChangedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MapChangedBuilder &operator=(const MapChangedBuilder &);
  flatbuffers::Offset<MapChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MapChanged>(end);
    return o;
  }
};

inline flatbuffers::Offset<MapChanged> CreateMapChanged(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> location = 0,
    flatbuffers::Offset<flatbuffers::String> imagemd5 = 0) {
  MapChangedBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_imagemd5(imagemd5);
  builder_.add_location(location);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<MapChanged> CreateMapChangedDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    const char *name = nullptr,
    const char *location = nullptr,
    const char *imagemd5 = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto location__ = location ? _fbb.CreateString(location) : 0;
  auto imagemd5__ = imagemd5 ? _fbb.CreateString(imagemd5) : 0;
  return monocle::CreateMapChanged(
      _fbb,
      token,
      name__,
      location__,
      imagemd5__);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_MAPCHANGED_MONOCLE_H_
