// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ONVIFUSERLEVEL_MONOCLE_H_
#define FLATBUFFERS_GENERATED_ONVIFUSERLEVEL_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class ONVIFUserlevel : int8_t {
  Anonymous = 1,
  User = 2,
  Operator = 3,
  Administrator = 4,
  MIN = Anonymous,
  MAX = Administrator
};

inline const ONVIFUserlevel (&EnumValuesONVIFUserlevel())[4] {
  static const ONVIFUserlevel values[] = {
    ONVIFUserlevel::Anonymous,
    ONVIFUserlevel::User,
    ONVIFUserlevel::Operator,
    ONVIFUserlevel::Administrator
  };
  return values;
}

inline const char * const *EnumNamesONVIFUserlevel() {
  static const char * const names[5] = {
    "Anonymous",
    "User",
    "Operator",
    "Administrator",
    nullptr
  };
  return names;
}

inline const char *EnumNameONVIFUserlevel(ONVIFUserlevel e) {
  if (flatbuffers::IsOutRange(e, ONVIFUserlevel::Anonymous, ONVIFUserlevel::Administrator)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(ONVIFUserlevel::Anonymous);
  return EnumNamesONVIFUserlevel()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_ONVIFUSERLEVEL_MONOCLE_H_
