// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ONVIFUSERCHANGED_MONOCLE_H_
#define FLATBUFFERS_GENERATED_ONVIFUSERCHANGED_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

#include "onvifuserlevel_generated.h"

namespace monocle {

struct ONVIFUserChanged;

struct ONVIFUserChanged FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_USERNAME = 6,
    VT_ONVIFUSERLEVEL = 8
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  ONVIFUserlevel onvifuserlevel() const {
    return static_cast<ONVIFUserlevel>(GetField<int8_t>(VT_ONVIFUSERLEVEL, 1));
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           VerifyField<int8_t>(verifier, VT_ONVIFUSERLEVEL) &&
           verifier.EndTable();
  }
};

struct ONVIFUserChangedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(ONVIFUserChanged::VT_TOKEN, token, 0);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(ONVIFUserChanged::VT_USERNAME, username);
  }
  void add_onvifuserlevel(ONVIFUserlevel onvifuserlevel) {
    fbb_.AddElement<int8_t>(ONVIFUserChanged::VT_ONVIFUSERLEVEL, static_cast<int8_t>(onvifuserlevel), 1);
  }
  explicit ONVIFUserChangedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ONVIFUserChangedBuilder &operator=(const ONVIFUserChangedBuilder &);
  flatbuffers::Offset<ONVIFUserChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ONVIFUserChanged>(end);
    return o;
  }
};

inline flatbuffers::Offset<ONVIFUserChanged> CreateONVIFUserChanged(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    flatbuffers::Offset<flatbuffers::String> username = 0,
    ONVIFUserlevel onvifuserlevel = ONVIFUserlevel::Anonymous) {
  ONVIFUserChangedBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_username(username);
  builder_.add_onvifuserlevel(onvifuserlevel);
  return builder_.Finish();
}

inline flatbuffers::Offset<ONVIFUserChanged> CreateONVIFUserChangedDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    const char *username = nullptr,
    ONVIFUserlevel onvifuserlevel = ONVIFUserlevel::Anonymous) {
  auto username__ = username ? _fbb.CreateString(username) : 0;
  return monocle::CreateONVIFUserChanged(
      _fbb,
      token,
      username__,
      onvifuserlevel);
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_ONVIFUSERCHANGED_MONOCLE_H_
