// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RECEIVERSTATE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_RECEIVERSTATE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class ReceiverState : int8_t {
  NotConnected = 0,
  Connecting = 1,
  Connected = 2,
  MIN = NotConnected,
  MAX = Connected
};

inline const ReceiverState (&EnumValuesReceiverState())[3] {
  static const ReceiverState values[] = {
    ReceiverState::NotConnected,
    ReceiverState::Connecting,
    ReceiverState::Connected
  };
  return values;
}

inline const char * const *EnumNamesReceiverState() {
  static const char * const names[4] = {
    "NotConnected",
    "Connecting",
    "Connected",
    nullptr
  };
  return names;
}

inline const char *EnumNameReceiverState(ReceiverState e) {
  if (e < ReceiverState::NotConnected || e > ReceiverState::Connected) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReceiverState()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_RECEIVERSTATE_MONOCLE_H_
