// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RECEIVERMODE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_RECEIVERMODE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class ReceiverMode : int8_t {
  AutoConnect = 0,
  AlwaysConnect = 1,
  NeverConnect = 2,
  MIN = AutoConnect,
  MAX = NeverConnect
};

inline const ReceiverMode (&EnumValuesReceiverMode())[3] {
  static const ReceiverMode values[] = {
    ReceiverMode::AutoConnect,
    ReceiverMode::AlwaysConnect,
    ReceiverMode::NeverConnect
  };
  return values;
}

inline const char * const *EnumNamesReceiverMode() {
  static const char * const names[4] = {
    "AutoConnect",
    "AlwaysConnect",
    "NeverConnect",
    nullptr
  };
  return names;
}

inline const char *EnumNameReceiverMode(ReceiverMode e) {
  if (flatbuffers::IsOutRange(e, ReceiverMode::AutoConnect, ReceiverMode::NeverConnect)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReceiverMode()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_RECEIVERMODE_MONOCLE_H_
