// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RECORDINGJOBLOGMESSAGE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_RECORDINGJOBLOGMESSAGE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

#include "logmessage_generated.h"
#include "severity_generated.h"

namespace monocle {

struct RecordingJobLogMessage;
struct RecordingJobLogMessageBuilder;

struct RecordingJobLogMessage FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RecordingJobLogMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORDINGTOKEN = 4,
    VT_TOKEN = 6,
    VT_MESSAGE = 8
  };
  uint64_t recordingtoken() const {
    return GetField<uint64_t>(VT_RECORDINGTOKEN, 0);
  }
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  const monocle::LogMessage *message() const {
    return GetPointer<const monocle::LogMessage *>(VT_MESSAGE);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_RECORDINGTOKEN) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyTable(message()) &&
           verifier.EndTable();
  }
};

struct RecordingJobLogMessageBuilder {
  typedef RecordingJobLogMessage Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_recordingtoken(uint64_t recordingtoken) {
    fbb_.AddElement<uint64_t>(RecordingJobLogMessage::VT_RECORDINGTOKEN, recordingtoken, 0);
  }
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(RecordingJobLogMessage::VT_TOKEN, token, 0);
  }
  void add_message(flatbuffers::Offset<monocle::LogMessage> message) {
    fbb_.AddOffset(RecordingJobLogMessage::VT_MESSAGE, message);
  }
  explicit RecordingJobLogMessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<RecordingJobLogMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RecordingJobLogMessage>(end);
    return o;
  }
};

inline flatbuffers::Offset<RecordingJobLogMessage> CreateRecordingJobLogMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t recordingtoken = 0,
    uint64_t token = 0,
    flatbuffers::Offset<monocle::LogMessage> message = 0) {
  RecordingJobLogMessageBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_recordingtoken(recordingtoken);
  builder_.add_message(message);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_RECORDINGJOBLOGMESSAGE_MONOCLE_H_
