// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RECORDINGJOBREMOVED_MONOCLE_H_
#define FLATBUFFERS_GENERATED_RECORDINGJOBREMOVED_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct RecordingJobRemoved;

struct RecordingJobRemoved FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORDINGTOKEN = 4,
    VT_TOKEN = 6
  };
  uint64_t recordingtoken() const {
    return GetField<uint64_t>(VT_RECORDINGTOKEN, 0);
  }
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_RECORDINGTOKEN) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           verifier.EndTable();
  }
};

struct RecordingJobRemovedBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_recordingtoken(uint64_t recordingtoken) {
    fbb_.AddElement<uint64_t>(RecordingJobRemoved::VT_RECORDINGTOKEN, recordingtoken, 0);
  }
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(RecordingJobRemoved::VT_TOKEN, token, 0);
  }
  explicit RecordingJobRemovedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  RecordingJobRemovedBuilder &operator=(const RecordingJobRemovedBuilder &);
  flatbuffers::Offset<RecordingJobRemoved> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<RecordingJobRemoved>(end);
    return o;
  }
};

inline flatbuffers::Offset<RecordingJobRemoved> CreateRecordingJobRemoved(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t recordingtoken = 0,
    uint64_t token = 0) {
  RecordingJobRemovedBuilder builder_(_fbb);
  builder_.add_token(token);
  builder_.add_recordingtoken(recordingtoken);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_RECORDINGJOBREMOVED_MONOCLE_H_
