// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STREAMINGPROTOCOL_MONOCLE_H_
#define FLATBUFFERS_GENERATED_STREAMINGPROTOCOL_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class StreamingProtocol : int8_t {
  UDPUnicast = 0,
  TCPInterleaved = 1,
  UDPMulticast = 2,
  RTPMulticast = 3,
  HTTPUnicast = 4,
  MIN = UDPUnicast,
  MAX = HTTPUnicast
};

inline const StreamingProtocol (&EnumValuesStreamingProtocol())[5] {
  static const StreamingProtocol values[] = {
    StreamingProtocol::UDPUnicast,
    StreamingProtocol::TCPInterleaved,
    StreamingProtocol::UDPMulticast,
    StreamingProtocol::RTPMulticast,
    StreamingProtocol::HTTPUnicast
  };
  return values;
}

inline const char * const *EnumNamesStreamingProtocol() {
  static const char * const names[] = {
    "UDPUnicast",
    "TCPInterleaved",
    "UDPMulticast",
    "RTPMulticast",
    "HTTPUnicast",
    nullptr
  };
  return names;
}

inline const char *EnumNameStreamingProtocol(StreamingProtocol e) {
  if (e < StreamingProtocol::UDPUnicast || e > StreamingProtocol::HTTPUnicast) return "";
  const size_t index = static_cast<int>(e);
  return EnumNamesStreamingProtocol()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_STREAMINGPROTOCOL_MONOCLE_H_
