// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TOKEN_MONOCLE_H_
#define FLATBUFFERS_GENERATED_TOKEN_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct TOKEN;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) TOKEN FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t token_;

 public:
  TOKEN() {
    memset(static_cast<void *>(this), 0, sizeof(TOKEN));
  }
  TOKEN(uint64_t _token)
      : token_(flatbuffers::EndianScalar(_token)) {
  }
  uint64_t token() const {
    return flatbuffers::EndianScalar(token_);
  }
};
FLATBUFFERS_STRUCT_END(TOKEN, 8);

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_TOKEN_MONOCLE_H_
