// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRACKTYPE_MONOCLE_H_
#define FLATBUFFERS_GENERATED_TRACKTYPE_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

enum class TrackType : int8_t {
  Video = 0,
  Audio = 1,
  Metadata = 2,
  ObjectDetector = 3,
  MIN = Video,
  MAX = ObjectDetector
};

inline const TrackType (&EnumValuesTrackType())[4] {
  static const TrackType values[] = {
    TrackType::Video,
    TrackType::Audio,
    TrackType::Metadata,
    TrackType::ObjectDetector
  };
  return values;
}

inline const char * const *EnumNamesTrackType() {
  static const char * const names[] = {
    "Video",
    "Audio",
    "Metadata",
    "ObjectDetector",
    nullptr
  };
  return names;
}

inline const char *EnumNameTrackType(TrackType e) {
  if (e < TrackType::Video || e > TrackType::ObjectDetector) return "";
  const size_t index = static_cast<int>(e);
  return EnumNamesTrackType()[index];
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_TRACKTYPE_MONOCLE_H_
