// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USERCHANGED_MONOCLE_H_
#define FLATBUFFERS_GENERATED_USERCHANGED_MONOCLE_H_

#include "flatbuffers/flatbuffers.h"

namespace monocle {

struct UserChanged;
struct UserChangedBuilder;

struct UserChanged FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UserChangedBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_GROUP = 6
  };
  uint64_t token() const {
    return GetField<uint64_t>(VT_TOKEN, 0);
  }
  uint64_t group() const {
    return GetField<uint64_t>(VT_GROUP, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TOKEN) &&
           VerifyField<uint64_t>(verifier, VT_GROUP) &&
           verifier.EndTable();
  }
};

struct UserChangedBuilder {
  typedef UserChanged Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_token(uint64_t token) {
    fbb_.AddElement<uint64_t>(UserChanged::VT_TOKEN, token, 0);
  }
  void add_group(uint64_t group) {
    fbb_.AddElement<uint64_t>(UserChanged::VT_GROUP, group, 0);
  }
  explicit UserChangedBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UserChanged> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UserChanged>(end);
    return o;
  }
};

inline flatbuffers::Offset<UserChanged> CreateUserChanged(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t token = 0,
    uint64_t group = 0) {
  UserChangedBuilder builder_(_fbb);
  builder_.add_group(group);
  builder_.add_token(token);
  return builder_.Finish();
}

}  // namespace monocle

#endif  // FLATBUFFERS_GENERATED_USERCHANGED_MONOCLE_H_
